# Site settings
title: Virtual Design Master
email: eric@discoposse.com
description: > # this means to ignore newlines until "baseurl:"
  Building the data centers of today, and the clouds of tomorrow.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: vdmchallenge
github_username:  virtualdesignmaster
host: 0.0.0.0

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 3
paginate_path: "blog/page:num"
